# import setuptools

# setuptools.setup(
#     name='jobsearchenginefortechgraduates',
#     version='1.0',
#     packages=setuptools.find_packages(),
#     install_requires=[
#         'annotated-types==0.7.0',
#         'anyio==4.7.0',
#         'blinker==1.9.0',
#         'certifi==2024.8.30',
#         'charset-normalizer==3.4.0',
#         'click==8.1.7',
#         'colorama==0.4.6',
#         'dnspython==2.7.0',
#         'email_validator==2.2.0',
#         'fastapi==0.115.6',
#         'feedparser==6.0.11',
#         'Flask==3.1.0',
#         'h11==0.14.0',
#         'idna==3.10',
#         'itsdangerous==2.2.0',
#         'Jinja2==3.1.4',
#         'MarkupSafe==3.0.2',
#         'mysql-connector-python==9.1.0',
#         'pydantic==2.10.3',
#         'pydantic_core==2.27.1',
#         'requests==2.32.3',
#         'sgmllib3k==1.0.0',
#         'sniffio==1.3.1',
#         'starlette==0.41.3',
#         'typing_extensions==4.12.2',
#         'urllib3==2.2.3',
#         'uvicorn==0.32.1',
#         'Werkzeug==3.1.3',
#         'cryptography==44.0.0',
#     ],
# )
import setuptools

setuptools.setup(
    name='jobsearchenginefortechgraduates',
    version='1.0',
    description='A Python-based backend application for job search functionalities and geographical data processing',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    packages=setuptools.find_packages(),
    install_requires=[
        'annotated-types==0.7.0',
        'anyio==4.7.0',
        'argon2-cffi==23.1.0',
        'argon2-cffi-bindings==21.2.0',
        'blinker==1.9.0',
        'certifi==2024.8.30',
        'cffi==1.17.1',
        'charset-normalizer==3.4.0',
        'click==8.1.7',
        'colorama==0.4.6',
        'cryptography==44.0.0',
        'Deprecated==1.2.15',
        'dnspython==2.7.0',
        'email_validator==2.2.0',
        'fastapi==0.115.6',
        'feedparser==6.0.11',
        'Flask==3.1.0',
        'h11==0.14.0',
        'idna==3.10',
        'itsdangerous==2.2.0',
        'Jinja2==3.1.4',
        'limits==3.14.1',
        'loguru==0.7.0',
        'MarkupSafe==3.0.2',
        'mysql-connector-python==9.1.0',
        'packaging==24.2',
        'prometheus-client==0.17.1',
        'pycparser==2.22',
        'pydantic==2.10.3',
        'pydantic_core==2.27.1',
        'python-dotenv==1.0.1',
        'redis==5.2.1',
        'requests==2.32.3',
        'sgmllib3k==1.0.0',
        'slowapi==0.1.9',
        'sniffio==1.3.1',
        'starlette==0.41.3',
        'typing_extensions==4.12.2',
        'urllib3==2.2.3',
        'uvicorn==0.32.1',
        'Werkzeug==3.1.3',
        'win32-setctime==1.2.0',
        'wrapt==1.17.0',
        'httpx==0.28.1',
        'pytest==8.3.4',
    ],
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
    ],
    python_requires='>=3.7',
)
